name: dloc
version: 1.0.0
description: A command-line application to count line of codes in Dart.
homepage: https://github.com/SigmaInformatique
author: Sigma Informatique <github@sigma.fr>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args:
  logging:

dev_dependencies:
  test:

executables:
  dloc: dloc